// You can find instructions for this file here:
// http://www.treeview.net

// Decide if the names are links or just the icons
USETEXTLINKS = 1  //replace 0 with 1 for hyperlinks

// Decide if the tree is to start all open or just showing the root folders
STARTALLOPEN = 0 //replace 0 with 1 to show the whole tree

ICONPATH = '../assets/images/main/tree/' //change if the gif's folder is a subfolder, for example: 'images/'


foldersTree = gFld("<a href=welcome.jsp target=main><font color=blue size=2>正字標記管理系統</font></a>", "")
//證書資料管理作業
	aux1 = insFld(foldersTree, gFld("證書資料管理作業", ""))
		insDoc(aux1, gLnk("R", "新申請案", "../do/cr/newApplication"))
//		insDoc(aux1, gLnk("R", "上支新申請案-中文證書", "../do/common/realtimeMenuForm?functId=CNM1910&caseNo=CR09300096"))
//		insDoc(aux1, gLnk("R", "上支新申請案-證書英文譯本", "../do/common/realtimeMenuForm?functId=CNM1920&caseNo=CR09300096"))
//		insDoc(aux1, gLnk("R", "上支新申請案 之 審核表 按鈕", "../do/common/realtimeMenuForm?functId=CNM1940&facNo=9903366800"))
		insDoc(aux1, gLnk("R", "換證管理", "../do/cr/changeApplication"))
//		insDoc(aux1, gLnk("R", "換證管理-CNS名稱變更/改新品目證書處理明細列印", "../do/common/realtimeMenuForm?functId=CNM1950"))
//		insDoc(aux1, gLnk("R", "上支換證管理 之 審核表 按鈕", "../do/common/realtimeMenuForm?functId=CNM1940&facNo=9903366800"))
		insDoc(aux1, gLnk("R", "廢止管理", "../do/cr/aboApplication"))
//		insDoc(aux1, gLnk("R", "廢止管理-CNS品目廢止證書處理明細", "../do/common/realtimeMenuForm?functId=CNM1960"))
		insDoc(aux1, gLnk("R", "廠商管理", "../do/cr/factory"))
		insDoc(aux1, gLnk("R", "公告管理", "../do/cr/bulletin"))
//		insDoc(aux1, gLnk("R", "公告管理報表-核准使用/撤銷/廢止正字標記產品一覽表", ""))
//		insDoc(aux1, gLnk("R", "公告管理報表-核准使用/撤銷/廢止正字標記產品一覽表(含轉Word檔)", "../do/common/realtimeMenuForm?functId=CNM1970"))
//		insDoc(aux1, gLnk("R", "公告管理報表-證書撤銷廢止未公告清冊", "../do/common/realtimeMenuForm?functId=CNM1980"))
		insDoc(aux1, gLnk("R", "證書資料管理", "../do/cr/certificate"))
//		insDoc(aux1, gLnk("R", "上支證書資料管理 之 審核表 按鈕", "../do/common/realtimeMenuForm?functId=CNM1940&facNo=9903366800"))
	aux2 = insFld(aux1, gFld("證書資料列印"))
		insDoc(aux2, gLnk("R", "申請案辦理進度明細", "../do/common/realtimeMenuForm?functId=CNM1710"))
		insDoc(aux2, gLnk("R", "申請案發證明細表", "../do/common/realtimeMenuForm?functId=CNM1720"))
		insDoc(aux2, gLnk("R", "申請案發證廠商列表", "../do/common/realtimeMenuForm?functId=CNM1730"))
		insDoc(aux2, gLnk("R", "申請案核駁明細", "../do/common/realtimeMenuForm?functId=CNM1740"))
		insDoc(aux2, gLnk("R", "申請案逾期通知明細", "../do/common/realtimeMenuForm?functId=CNM1750"))
		insDoc(aux2, gLnk("R", "證書撤銷廢止清冊", "../do/common/realtimeMenuForm?functId=CNM1760"))
		insDoc(aux2, gLnk("R", "通知換證逾期未回明細表", ""))
		insDoc(aux2, gLnk("R", "換證逾期未結案清冊", ""))
	aux3 = insFld(aux1, gFld("產品廠商清冊列印"))
		insDoc(aux3, gLnk("R", "正字標記廠商貼條", "../do/common/realtimeMenuForm?functId=CNM1810"))
		insDoc(aux3, gLnk("R", "廠商卷宗標籤列印", "../do/common/realtimeMenuForm?functId=CNM1820"))
		insDoc(aux3, gLnk("R", "正字標記產品品目廠商及證書數量清冊", "../do/common/realtimeMenuForm?functId=CNM1830"))
		insDoc(aux3, gLnk("R", "類別及郵遞區號區分之工廠名稱清冊", "../do/common/realtimeMenuForm?functId=CNM1840"))
		insDoc(aux3, gLnk("R", "類別區分廠商資料清冊", "../do/common/realtimeMenuForm?functId=CNM1850"))
		insDoc(aux3, gLnk("R", "正字標記產品及廠商目錄（精簡版）", ""))
//廠商普查管理作業
	aux1 = insFld(foldersTree, gFld("廠商普查管理作業"))
	aux2 = insFld(aux1, gFld("廠商普查執行作業"))
		insDoc(aux2, gLnk("R", "抽樣檢驗作業", "../do/fa/sampleExam"))
//		insDoc(aux2, gLnk("R", "上一列 抽樣檢驗作業 之 檢驗項目及收費明細表", "../do/common/realtimeMenuForm?functId=CNM2530"))
//		insDoc(aux2, gLnk("R", "上一列 抽樣檢驗作業 之 產品檢驗紀錄表 按鈕", "../do/common/realtimeMenuForm?functId=CNM2540&id=1"))
//		insDoc(aux2, gLnk("R", "上一列 抽樣檢驗作業 之 產品檢驗抽驗單列印 按鈕", "../do/common/realtimeMenuForm?functId=CNM2110&facNo=0100048900&licenseNo=00001&licenseNos=00001,00002,00003,00004,00005,00006,00007&faScheduleId=5"))
		insDoc(aux2, gLnk("R", "品管評鑑作業", "../do/fa/qualityExam"))
		insDoc(aux2, gLnk("R", "普查執行預定狀況", "../do/fa/examSchedule"))
//		insDoc(aux2, gLnk("R", "上支的列印按鈕--廠商普查列印表列印", "../do/common/realtimeMenuForm?functId=CNM2560"))//新增
//		insDoc(aux2, gLnk("R", "普查執行預定狀況--廠商年度普查次數不足清冊列印", "../do/common/realtimeMenuForm?functId=CNM2570")) //新增 2004/04/28
//        insDoc(aux2, gLnk("R", "普查執行預定狀況--廠商異常未辦清冊列印", "../do/common/realtimeMenuForm?functId=CNM2580")) //新增 2004/04/28
	aux3 = insFld(aux1, gFld("廠商普查異常資料維護"))
		insDoc(aux3, gLnk("R", "普查異常管理", "../do/fa/examException"))
		insDoc(aux3, gLnk("R", "普查廠商申請作業", "../do/fa/facNewApp"))
//		insDoc(aux3, gLnk("R", "上支普查廠商申請作業-監督試驗能力評估報告書列印", "../do/common/realtimeMenuForm?functId=CNM2590&facId=2&licenseNo=00005&id=1"))
	aux4 = insFld(aux1, gFld("廠商年度普查查詢"))
		insDoc(aux4, gLnk("R", "廠商年度普查查詢", "../do/fa/factoryScheduleQuery"))
		insDoc(aux4, gLnk("R", "產品普查執行狀況查詢", "../do/fa/productExamQuery"))
	aux5 = insFld(aux1, gFld("廠商普查報表列印"))
		insDoc(aux5, gLnk("R", "廠商普查辦理方式清冊","../do/common/realtimeMenuForm?functId=CNM2410")) //新增 2004/04/26
		insDoc(aux5, gLnk("R", "廠商現況清冊列印", "../do/common/realtimeMenuForm?functId=CNM2420"))
//產品品目管理作業
	aux1 = insFld(foldersTree, gFld("產品品目管理作業"))
		insDoc(aux1, gLnk("R", "增列品目管理", "../do/in/addApplication"))
//        insDoc(aux1, gLnk("R", "上支的列印按鈕--檢驗項目及收費明細表", "../do/common/realtimeMenuForm?functId=CNM3820&mainNo=0045"))
//		insDoc(aux1, gLnk("R", "上支的列印按鈕--正字標記品目分類表", "../do/common/realtimeMenuForm?functId=CNM3810"))
		insDoc(aux1, gLnk("R", "修正品目項目", "../do/in/modApplication"))
		insDoc(aux1, gLnk("R", "廢止產品項目", "../do/in/aboApplication"))
//		insDoc(aux1, gLnk("R", "上支廢止產品項目-正字標記品目廢止一覽表", "../do/common/realtimeMenuForm?functId=CNM3850"))
		insDoc(aux1, gLnk("R", "品目公告管理", "../do/in/bulletin"))
//		insDoc(aux1, gLnk("R", "上一列 品目公告管理 之 正字標記品目增列廢止公告 按鈕", "../do/common/realtimeMenuForm?functId=CNM3400&caseNo=123"))
	aux2 = insFld(aux1, gFld("檢驗項目及收費明細表管理"))
		insDoc(aux2, gLnk("R", "檢驗項目及收費明細表維護", "../do/in/fee"))
		insDoc(aux2, gLnk("R", "檔案管理", "../do/in/file"))
	aux3 = insFld(aux1, gFld("品目基本資料"))
		insDoc(aux3, gLnk("R", "品目基本資料", "../do/in/commodity"))
	aux4 = insFld(aux1, gFld("產品品目報表列印"))
		insDoc(aux4, gLnk("R", "正字標記品目『增列』作業辦理狀況表", "../do/common/realtimeMenuForm?functId=CNM3710"))
		insDoc(aux4, gLnk("R", "正字標記品目『增列』作業未結案件列表", "../do/common/realtimeMenuForm?functId=CNM3720"))
		insDoc(aux4, gLnk("R", "正字標記產品品目目錄", "../do/common/realtimeMenuForm?functId=CNM3730"))  //新增 2004/05/03
		insDoc(aux4, gLnk("R", "正字標記產品品目分類目錄", "../do/common/realtimeMenuForm?functId=CNM3740")) //新增 2004/05/04
		insDoc(aux4, gLnk("R", "正字標記品目適用標準異動狀況一覽表(Excel)", "../do/common/realtimeMenuForm?functId=CNM3750"))
		insDoc(aux4, gLnk("R", "廢止正字標記品目一覽表", "../do/common/realtimeMenuForm?functId=CNM3760"))
		insDoc(aux4, gLnk("R", "正字標記品目檢驗費用一覽表", "../do/common/realtimeMenuForm?functId=CNM3770")) //新增 2004/05/04
		insDoc(aux4, gLnk("R", "正字標記品目類別增列/修正/廢止明細表", "../do/common/realtimeMenuForm?functId=CNM3780"))
//認可機構管理
	aux1 = insFld(foldersTree, gFld("認可機構管理作業"))
	aux2 = insFld(aux1, gFld("品管驗證認可機構管理"))
		insDoc(aux2, gLnk("R", "CNAB認證分類與品目範圍設定", "../do/qt/qcNACEField"))
//		insDoc(aux2, gLnk("R", "上支的列印按鈕--CNAB認證分類與品目範圍對照表列印", "../do/common/realtimeMenuForm?functId=CNM4310"))//新增
		insDoc(aux2, gLnk("R", "品管驗證認可機構申請管理", "../do/qt/qcOrg"))
		insDoc(aux2, gLnk("R", "品管驗證認可機構異動管理", "../do/qt/qcOrgFieldHistory"))
		insDoc(aux2, gLnk("R", "品管驗證認可機構撤銷/廢止/展延", "../do/qt/qcOrgAboLish"))
		insDoc(aux2, gLnk("R", "品管驗證認可機構列印", "../do/common/realtimeMenuForm?functId=CNM4150"))
	aux3 = insFld(aux1, gFld("檢驗認可機構管理"))
		insDoc(aux3, gLnk("R", "檢測領域公告管理", "../do/qt/isField"))
//        insDoc(aux3, gLnk("R", "上支的列印按鈕--領域檢測項目及其適用標準表列印", "../do/common/realtimeMenuForm?functId=CNM4320"))//新增
		insDoc(aux3, gLnk("R", "檢驗認可機構申請管理", "../do/qt/isOrg"))
//		insDoc(aux3, gLnk("R", "上支的列印-試驗室認可登錄證書", "../do/common/realtimeMenuForm?functId=CNM4330&id=00001"))
		insDoc(aux3, gLnk("R", "檢驗認可機構異動管理", "../do/qt/isModify"))
		insDoc(aux3, gLnk("R", "NACE管理", "../do/qt/qcNaceMaintain"))
		insDoc(aux3, gLnk("R", "檢驗認可機構撤銷/廢止/展延", ""))
		insDoc(aux3, gLnk("R", "檢驗認可機構列印", "../do/common/realtimeMenuForm?functId=CNM4250"))
//績效統計
	aux1 = insFld(foldersTree, gFld("績效統計作業"))
	aux2 = insFld(aux1, gFld("證書績效統計"))
		insDoc(aux2, gLnk("R", "正字標記產品廠商類別統計表", "../do/common/realtimeMenuForm?functId=CNM5110"))
		insDoc(aux2, gLnk("R", "正字標記產品類別月統計表（各類別及總表）", ""))
		insDoc(aux2, gLnk("R", "標準推行及管理績效統計表", "../do/common/realtimeMenuForm?functId=CNM5130"))
		insDoc(aux2, gLnk("R", "正字標記產品品目、廠商及證書數量類別統計表", "../do/common/realtimeMenuForm?functId=CNM5140"))
		insDoc(aux2, gLnk("R", "正字標記工廠證書數統計表", "../do/common/realtimeMenuForm?functId=CNM5150"))
		insDoc(aux2, gLnk("R", "正字標記產品品目廠商及證書數量統計表", "../do/common/realtimeMenuForm?functId=CNM5160"))
		insDoc(aux2, gLnk("R", "新增／廢止／註銷／撤銷廠商統計表", "../do/common/realtimeMenuForm?functId=CNM5170"))
		insDoc(aux2, gLnk("R", "正字標記管理推行業務", "../do/common/realtimeMenuForm?functId=CNM5180"))
		insDoc(aux2, gLnk("R", "正字標記管理列印", "../do/common/realtimeMenuForm?functId=CNM5190"))
	aux3 = insFld(aux1, gFld("普查管理績效"))
		insDoc(aux3, gLnk("R", "正字標記產品管理統計報表(品管督導數)", "../do/common/realtimeMenuForm?functId=CNM5210"))
		insDoc(aux3, gLnk("R", "正字標記產品管理統計報表(產品抽驗數)", "../do/common/realtimeMenuForm?functId=CNM5220"))
		insDoc(aux3, gLnk("R", "正字標記產品抽樣檢驗結果統計報表", "../do/common/realtimeMenuForm?functId=CNM5230"))
		insDoc(aux3, gLnk("R", "新申請案品管評鑑/產品檢驗執行單位統計表", "../do/common/realtimeMenuForm?functId=CNM5240"))
		insDoc(aux3, gLnk("R", "申請變更品管/產品檢驗認可機構統計表", "../do/common/realtimeMenuForm?functId=CNM5250"))
	aux4 = insFld(aux1, gFld("產品品目績效"))
		insDoc(aux4, gLnk("R", "正字標記產品檢驗方式統計表列印", "../do/common/realtimeMenuForm?functId=CNM5310"))
		insDoc(aux4, gLnk("R", "正字標記品目類別增列／修正／廢止統計表", "../do/common/realtimeMenuForm?functId=CNM5320"))
		insDoc(aux4, gLnk("R", "正字標記品目統計表", "../do/common/realtimeMenuForm?functId=CNM5330"))
	aux5 = insFld(aux1, gFld("普查執行單位績效"))
		insDoc(aux5, gLnk("R", "品管評鑑/產品檢驗方式執行狀況表", "../do/common/realtimeMenuForm?functId=CNM5410"))
		insDoc(aux5, gLnk("R", "本局/認可機構逾期案件一覽表", "../do/common/realtimeMenuForm?functId=CNM5420"))
		insDoc(aux5, gLnk("R", "認可機構產品檢驗/品管追查執行數量月統計表", "../do/common/realtimeMenuForm?functId=CNM5430"))
	aux6 = insFld(aux1, gFld("月績效報表檔案管理"))
		insDoc(aux6, gLnk("R", "月績效報表檔案管理", "../do/eff/monthlyEffects"))
//線上查詢
	aux1 = insFld(foldersTree, gFld("網路查詢作業"))
		insDoc(aux1, gLnk("R", "正字標記產品品目查詢", "../do/net/productQuery"))
		insDoc(aux1, gLnk("R", "正字標記廠商資料查詢", "../do/net/factoryQuery"))
		insDoc(aux1, gLnk("R", "正字標記證書資料查詢", "../do/net/certificateQuery"))
		insDoc(aux1, gLnk("R", "正字標記認可品質管理驗證機構名錄", "../do/common/realtimeMenuForm?functId=CNM6400"))
		insDoc(aux1, gLnk("R", "正字標記認可試驗室名錄", "../do/common/realtimeMenuForm?functId=CNM6500"))
		insDoc(aux1, gLnk("R", "正字標記新申請案進度查詢", "../do/net/newAppProgressQuery"))
//基本設定
	aux1 = insFld(foldersTree, gFld("基本設定作業"))
		insDoc(aux1, gLnk("R", "函稿設定", "../do/sy/documentDefine"))
		insDoc(aux1, gLnk("R", "郵區代碼", "../do/sy/postCode"))
		insDoc(aux1, gLnk("R", "報表管理", "../do/sy/reportManage"))
		insDoc(aux1, gLnk("R", "狀況代碼維護", "../do/sy/statusMaintain"))
		insDoc(aux1, gLnk("R", "資料代碼維護", "../do/sy/codeMaintain"))
		insDoc(aux1, gLnk("R", "系統給號維護", "../do/sy/numMaintain"))
		insDoc(aux1, gLnk("R", "函稿測試", "../do/common/documentMenuForm?functId=CNM1200"))
//系統維護
	aux1 = insFld(foldersTree, gFld("系統維護作業"))
		insDoc(aux1, gLnk("R", "使用者管理", "../do/sy/userManage"))
		insDoc(aux1, gLnk("R", "角色管理", "../do/sy/roleManage"))
		insDoc(aux1, gLnk("R", "使用者TO角色權限管理", "../do/sy/userToRoleManage"))
		insDoc(aux1, gLnk("R", "角色TO功能權限管理", "../do/sy/roleToFunManage"))
		insDoc(aux1, gLnk("R", "資料匯出查詢作業", "../do/sy/dataExportQuery"))
		insDoc(aux1, gLnk("R", "公告管理", "../do/sy/bulletin"))
		insDoc(aux1, gLnk("R", "系統功能架構管理", "../do/sy/syFunFrameWork"))